### ISSUE TITLE
Cointype belong to Dash

### ISSUE THREAD

**Issue by Altcoin-Cash** [DreamTeamCoin3/DT3#2]
https://github.com/DreamTeamCoin3/DT3/blob/b526188b52e7cac1e5097042feca99b9843896b7/src/chainparams.cpp#L235

nExtCoinType = 5;
This should be a unique number for the coin, register this here: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by DreamTeamCoin3** [comment]
Thanks
*DREAM TEAM ADMIN*
